source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/windowrules.conf
env = QT_QPA_PLATFORMTHEME,qt6ct
env = ADW_DISABLE_PORTAL,0

