general {
    lock_cmd = pidof hyprlock || hyprlock       # Команда блокировки экрана
    before_sleep_cmd = loginctl lock-session    # Блокировать перед сном
    after_sleep_cmd = hyprctl dispatch dpms on  # Включить монитор после пробуждения
}

# Через 5 минут бездействия — уменьшить яркость
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# Через 10 минут бездействия — заблокировать экран
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# Через 15 минут бездействия — отправить в глубокий сон (systemctl suspend)
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
