# Размытие фона под Waybar
layerrule = blur match:namespace:waybar

# Формат: monitor = ИМЯ, РАЗРЕШЕНИЕ, ПОЗИЦИЯ, МАСШТАБ
monitor = , preferred, auto, 1.33

xwayland {
    force_zero_scaling = true
}

general {
    gaps_in = 5
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(719672ff) rgba(799dcbff) 45deg
    col.inactive_border = rgba(4e4e4eff)
    layout = dwindle
}

decoration {
    rounding = 8
    active_opacity = 1.0
    inactive_opacity = 0.85

    blur {
        enabled = true
        size = 10
        passes = 2
    }

    shadow {
	enabled = true
	range = 12
	render_power = 3
	color = rgba(1a1a1aee)
    }
}

animations {
    enabled = true
    bezier = myCurve, 0.27, 0.5, 0.29, 1.0
    animation = windows, 1, 5, myCurve
    animation = windowsOut, 1, 5, default, popin 80%
    animation = border, 1, 8, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 4, default, slide
}

