exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = waybar
exec-once = /usr/lib/polkit-kde-agent-1

# скрипт сам запустит правильный swaybg и swayosd-server
exec-once = ~/.local/bin/switch-theme.sh auto

exec-once = nm-applet --indicator
exec-once = hypridle
exec-once = swaync
exec-once = ~/.local/bin/battery-notifier.sh
