$mainMod = SUPER

# Переменные приложений
$terminal = alacritty -e tmux 
$fileManager = nautilus 
$menu = rofi -show drun -theme ~/.config/rofi/launchers/type-1/style-3.rasi -show-icons

# Запуск основных программ
bind = $mainMod, Q, killactive, 
bind = $mainMod, R, exec, $terminal 
bind = $mainMod, E, exec, $fileManager 
bind = $mainMod, D, exec, $menu


# Безопасный выход из системы (Hyprland)
bind = $mainMod SHIFT, E, exit,

# Заблокировать экран через hyprlock
bind = $mainMod SHIFT, L, exec, hyprlock


# ======================================
# 		ОКНА
# ======================================

# Развернуть окно на весь экран (скрывает Waybar)
bind = $mainMod, F, fullscreen, 0

# Переключение фокуса между окнами
bind = $mainMod, H, movefocus, l 
bind = $mainMod, L, movefocus, r 
bind = $mainMod, K, movefocus, u 
bind = $mainMod, J, movefocus, d

# Перемещение окон местами
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r

# Изменение размеров активного окна
bind = $mainMod CTRL, H, resizeactive, -40 0     # Сузить по ширине
bind = $mainMod CTRL, L, resizeactive, 40 0      # Расширить по ширине
bind = $mainMod CTRL, K, resizeactive, 0 -40     # Уменьшить по высоте
bind = $mainMod CTRL, J, resizeactive, 0 40      # Увеличить по высоте


# =============================================
# 		РАБОЧИЕ СТОЛЫ
# =============================================

# Переключение рабочих столов (Workspaces)
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# Перенос окна на другой рабочий стол
bind = $mainMod SHIFT, 1, movetoworkspace, 1 
bind = $mainMod SHIFT, 2, movetoworkspace, 2 
bind = $mainMod SHIFT, 3, movetoworkspace, 3 
bind = $mainMod SHIFT, 4, movetoworkspace, 4 
bind = $mainMod SHIFT, 5, movetoworkspace, 5


# =============================================
#	      ГРОМКОСТЬ И ЯРКОСТЬ
# =============================================

# Управление громкостью (wpctl / PipeWire)
binde = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 2%+
binde = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# Управление яркостью экрана (brightnessctl)
binde = , XF86MonBrightnessUp, exec, brightnessctl set 2%+
binde = , XF86MonBrightnessDown, exec, brightnessctl set 2%-

# Включить/выключить микрофон кнопкой на клавиатуре (задержка на 0.2 секунды для корректной работы)
bind = , XF86AudioMicMute, exec, [ -f /tmp/mic_lock ] || (touch /tmp/mic_lock; wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle; sleep 0.2; rm -f /tmp/mic_lock)


# =======================================
#		СКРИНШОТЫ
# =======================================

# Скриншот выделенной области в буфер обмена (Print / Super + Shift + S)
bind = , Print, exec, mkdir -p ~/Pictures/Screenshots && grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/Screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png | wl-copy
bind = $mainMod SHIFT, S, exec, mkdir -p ~/Pictures/Screenshots && grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/Screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png | wl-copy

# Скриншот ВСЕГО экрана в буфер обмена (Super + Print)
bind = $mainMod, Print, exec, mkdir -p ~/Pictures/Screenshots && grim - | tee ~/Pictures/Screenshots/Screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png | wl-copy

# Переключение светлой/тёмной темы по Super + Shift + T
bind = SUPER SHIFT, T, exec, ~/.local/bin/toggle-theme.sh

# Переключение WireGuard VPN (Super + V)
bind = $mainMod, V, exec, nmcli connection show --active | grep -q wg0 && (nmcli connection down wg0 && notify-send "WireGuard" "VPN Отключен" -i network-offline) || (nmcli connection up wg0 && notify-send "WireGuard" "VPN Подключен" -i network-vpn)

