windowrule = match:class .*, workspace empty

# 2. Привязка приложений к рабочим столам
windowrule = match:class ^(firefox)$, workspace 1
windowrule = match:class ^(google-chrome)$, workspace 1
windowrule = match:class ^(zen-alpha)$, workspace 1

windowrule = match:class ^(Alacritty)$, workspace 2
windowrule = match:class ^(jetbrains-idea)$, workspace 2
windowrule = match:class ^(obsidian)$, workspace 2

windowrule = match:class ^(org.telegram.desktop)$, workspace 3
windowrule = match:class ^(discord)$, workspace 3

windowrule = match:class ^(org.gnome.Nautilus)$, workspace 4
windowrule = match:class ^(vlc)$, workspace 4

# 3. Диалоги и всплывающие окна — плавающими (float 1)
windowrule = match:class ^(pavucontrol)$, float 1
windowrule = match:title ^(Open File)$, float 1
windowrule = match:title ^(Save File)$, float 1
windowrule = match:title ^(Confirm to replace files)$, float 1

